### ISSUE TITLE
Document manual Skyminer image setup

### ISSUE THREAD

**Issue by jdknives** [skycoin/wiki#32]
We need to document the setup steps for users to go through to setup an equivalent of the miner images we provide. These steps should explain where to get the base image for the miner and how to configure and setup Skywire to the point where Skywire is installed and configured in the same way the user would have it setup with out own images. This will serve a dual purpose of documenting our image setup and allowing users to reproduce the setup should it be desired. 

Additionally, this may be used to document the various environment variables and conditionals we use in the autoconfig script so we have some documentation of this part of the image that we currently lack. This second part of the documentation may be put into a separate article if needed.

**Comment by 0pcom** [comment]
I'm unable to run the test server to preview the changes after installing all the dependencies!

```
$ mkdocs serve
INFO     -  Building documentation...
INFO     -  [macros] - Macros arguments: {'module_name': 'main',
            'modules': [], 'include_dir': '', 'include_yaml': [],
            'j2_block_start_string': '', 'j2_block_end_string': '',
            'j2_variable_start_string': '', 'j2_variable_end_string': '',
            'verbose': False}
INFO     -  [macros] - Extra variables (config file): ['social',
            'issue_url']
INFO     -  [macros] - Extra filters (module): ['pretty']
INFO     -  Cleaning site directory
INFO     -  The following pages exist in the docs directory, but are not
            included in the "nav" configuration:
              - brand.md
              - buywithsky.md
              - exchanges.md
              - info.md
              - meetups.md
              - news.md
              - partnerships.md
              - roadmap.md
              - timeline.md
              - videos.md
              - software/cxfx/social.md
              - software/cxo/social.md
              - software/skywire/about.md
              - software/skywire/discovery.md
              - software/skywire/social.md
              - software/skywire/devdocs/transports.md
              - software/skywire/setup/overview.md
              - software/skywire/setup/raspberrypi.md
ERROR    -  Error building page 'about.md': partials/source-date.html
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 33, in <module>
    sys.exit(load_entry_point('mkdocs==1.3.0', 'console_scripts', 'mkdocs')())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/mkdocs/__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/usr/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 63, in serve
    config = builder()
  File "/usr/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/lib/python3.10/site-packages/mkdocs/commands/build.py", line 314, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/usr/lib/python3.10/site-packages/mkdocs/commands/build.py", line 217, in _build_page
    output = template.render(context)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/d0mo/go/src/github.com/the-skycoin-project/skycoin-wiki/overrides/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/lib/python3.10/site-packages/material/base.html", line 164, in top-level template code
    {% block content %}
  File "/home/d0mo/go/src/github.com/the-skycoin-project/skycoin-wiki/overrides/main.html", line 50, in block 'content'
    {% include "partials/source-date.html" %}
  File "/usr/lib/python3.10/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: partials/source-date.html
```

I have the documentation started in the skywire wiki
